### ISSUE TITLE
Bracken executable is not in environment

### ISSUE THREAD

**Issue by CJREID** [maxlcummins/pipelord#15]
Looks like the bracken exectuable is in your Data folder according to the error below...

**/usr/bin/bash: /home/cajreid/Data/playground/Bracken/bracken: No such file or directory**

See also the shell command.

I also activated the environment and did ```which bracken``` and it wasn't there so I guess it needs to be added to the yaml?

```
Activating conda environment: /data/cajreid/pipelord2.1/.snakemake/conda/c5a272c9
/usr/bin/bash: /home/cajreid/Data/playground/Bracken/bracken: No such file or directory
[Mon Nov 22 14:21:36 2021]
Error in rule bracken:
    jobid: 123
    output: results/test/bracken/AVC111.bracken.txt, results/test/bracken/AVC111_bracken_species_report.txt
    log: logs/test/bracken/AVC111.bracken.log (check log file(s) for error message)
    conda-env: /data/cajreid/pipelord2.1/.snakemake/conda/c5a272c9
    shell:
        ~/Data/playground/Bracken/bracken -d /projects/AusGEM/databases/kraken2/minikraken2 -i results/test/kraken2/AVC111.report -o results/test/bracken/AVC111.bracken.txt -w results/test/bracken/AVC111_bracken_species_report.txt -r 100 -l S -t 1 2>&1 logs/test/bracken/AVC111.bracken.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Comment by maxlcummins** [comment]
This is fixed - snakemake will look in resources/tools/Bracken/bracken and if its not there it will download it. Probably I should add it as a path in the config instead but the bracken installation isnt too big and only need to be installed once so its not a big deal.

Cheers
